use_frameworks!

target 'RSCarouselViewLib_Example' do
  pod 'RSCarouselViewLib', :path => '../'

  target 'RSCarouselViewLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
